export const BlogData = [
    {
        id: 1,
        title: 'Rise Kohyang High School Selected as Honor Roll School',
        paragraph: 'Elias Cruz’s remarkable journey to earn his high school diploma and two associates degrees in the same week is…',
        image: 'https://brightstarschools.org/get/files/image/galleries/News_thumbnail_(1).jpg?resize=768x0',
        date: 'October 1, 2023',
        btn: 'Learn More',
    },
    {
        id: 2,
        title: 'Rise Kohyang High School Selected as Honor Roll School',
        paragraph: 'As high schools celebrate graduations this June, Elias Cruz, a senior at Stella High Charter Academy, a Bright Star…',
        image: 'https://brightstarschools.org/get/files/image/galleries/News_thumbnail_(1).jpg?resize=768x0',
        date: 'October 1, 2023',
        btn: 'Learn More',
    },
    {
        id: 3,
        title: 'Rise Kohyang High School Selected as Honor Roll School',
        paragraph: 'As high schools celebrate graduations this June, Elias Cruz, a senior at Stella High Charter Academy, a Bright Star…',
        image: 'https://brightstarschools.org/get/files/image/galleries/News_thumbnail_(1).jpg?resize=768x0',
        date: 'October 1, 2023',
        btn: 'Learn More',
    },
    {
        id: 4,
        title: 'Rise Kohyang High School Selected as Honor Roll School',
        paragraph: 'Today, we spotlight Mrs. Chanel Hungerford Williams, an Inclusion Specialist (SpEd) Teacher at Valor Academy Middle S…',
        image: 'https://brightstarschools.org/get/files/image/galleries/News_thumbnail_(1).jpg?resize=768x0',
        date: 'October 1, 2023',
        btn: 'Learn More',
    },
    {
        id: 5,
        title: 'Rise Kohyang High School Selected as Honor Roll School',
        paragraph: 'Elias Cruz’s remarkable journey to earn his high school diploma and two associates degrees in the same week is…',
        image: 'https://brightstarschools.org/get/files/image/galleries/News_thumbnail_(1).jpg?resize=768x0',
        date: 'October 1, 2023',
        btn: 'Learn More',
    },
    {
        id: 6,
        title: 'Rise Kohyang High School Selected as Honor Roll School',
        paragraph: 'Elias Cruz’s remarkable journey to earn his high school diploma and two associates degrees in the same week is…',
        image: 'https://brightstarschools.org/get/files/image/galleries/News_thumbnail_(1).jpg?resize=768x0',
        date: 'October 1, 2023',
        btn: 'Learn More',
    },
    {
        id: 7,
        title: 'Rise Kohyang High School Selected as Honor Roll School',
        paragraph: 'Elias Cruz’s remarkable journey to earn his high school diploma and two associates degrees in the same week is…',
        image: 'https://brightstarschools.org/get/files/image/galleries/News_thumbnail_(1).jpg?resize=768x0',
        date: 'October 1, 2023',
        btn: 'Learn More',
    },
]